### ISSUE TITLE
Ubuntu Saucy changed libturbojpeg.so to libturbojpeg.so.0.

### ISSUE THREAD

**Issue by RossBrunton** [Bumblebee-Project/bumblebee-ppa#24]
Not sure if this is the right place for this, but in Ubuntu Saucy (and I think Debian) they changed the name of the libturbojpeg library from "libturbojpeg.so" to "libturbojpeg.so.0", meaning that virtualgl can't find it. Linking libturbojpeg.so.0 to libturbojpeg.so works as a workaround.

    $ optirun -v bash
    [ 7712.238808] [INFO]Configured driver: nvidia
    [ 7712.621926] [INFO]Response: Yes. X is active.

    [ 7712.621948] [INFO]Running application using virtualgl.
    bash: error while loading shared libraries: libturbojpeg.so: cannot open shared object file: No such file or directory

**Comment by ArchangeGabriel** [comment]
Saucy isn’t supported anymore + the right solution was linking to .so symlink, closing.
