### ISSUE TITLE
Huge PPA update

### ISSUE THREAD

**Issue by ArchangeGabriel** [Bumblebee-Project/bumblebee-ppa#33]
A quite huge PPA update should be done:

- [x] remove packages from unsupported distro (will do that)
- [x] add utopic and vivid to GitHub (copy from trusty) (can do that if you want)
- [x] build primus-20141228 for all (not forgetting the libgl dependency change in the changelog)
- [ ] build virtualgl-2.4-1~beta1 (or something similar, don’t know the appropriate numbering scheme for beta snapshot) with either current trunk or effective 2.4beta1.
- [ ] build bumblebee-4.0 when this one is published.

@Vincent-C Will you be able to hande all that? I currently don’t have laptop running under Debian/Ubuntu to package and test all these, but I could try to setup a live USB in order to do so.

**Comment by Vincent-C** [comment]
@ArchangeGabriel, I can do most/all of that, although it's perhaps worth noting that I really only test my packages on Debian, not Ubuntu, so it'd be helpful for someone else to test those packages on an actual Ubuntu or Ubuntu-based environment. It's probably a good idea to push to the developer/testing PPA first, assuming people actually use that.

I was intending on waiting for the 4.0 release to come out first before updating the PPA, as I don't think there's anything urgent that's sitting in git right now, just a bunch of small misc fixes and updates.

**Comment by ArchangeGabriel** [comment]
Nice to hear that. :) Indeed, we should upload to the testing PPA first, I have people on the french forum OK to use it to test and report potential issues.

I agree with you that bumblebee should wait 4.0 before packaging updates, but I thought primus could be updated right now for instance, same for VirtualGL. But since Utopic and Vivid won’t have Bumblebee on the PPA before the 4.0 release, and because it’s much easier to do all these at once, I have no issue with not updating for now, I’ve just set up this list in the first place to be sure we don’t forget something. ;)

**Comment by Vincent-C** [comment]
Actually, would it be possible for you to take care of virtualgl? It's just that I haven't worked on any of the virtualgl packaging in the PPA before, and so you're likely more familiar with it than I am.

I'm waiting on Debian to get released and unfrozen so that I can update primus at the same time there as well. It's indeed easier to take care of everything at the same time. :)

**Comment by ArchangeGabriel** [comment]
OK, will see what I can do.

Do you know what is the current state of nvidia packaging in Ubuntu? I’m wondering whether our default paths and auto-detection is still working there.

**Comment by Vincent-C** [comment]
I don't know, but since it looks like Ubuntu's been stuck on nvidia-331 for a long time, I doubt anything much has changed.

**Comment by ArchangeGabriel** [comment]
Could you update bumblebee to ~distroppa2 right now with support for nvidia-340, 343 and 346? First two already are in the files but not pushed to the PPA, third one need to be added (I can do that if you want).

Bumblebee 4.0 might still be some weeks away, but some users are requesting this. Thanks!

**Comment by Vincent-C** [comment]
I currently don't have time to prepare package updates right now (really busy with school), may have a chance to work on this the weekend after next.

**Comment by Vincent-C** [comment]
@ArchangeGabriel @Lekensteyn I've updated the PPA with all changes that were pending in the github repo, and merged in all changes made to bbswitch/bumblebee/primus packaging in Debian/Ubuntu proper. Virtualgl packaging is being tracked in #30, and bumblebee 4.0 hasn't been released yet, so I'm going to go ahead and close this issue.
