### ISSUE TITLE
Support for NVIDIA 367

### ISSUE THREAD

**Issue by ArchangeGabriel** [Bumblebee-Project/bumblebee-ppa#35]
The modprobe file need to be updated, but also nvidia-modeset needs to be handled.

**Comment by ArchangeGabriel** [comment]
Changing that for nvidia-367 and @bluca. And don’t care about supplemental modules anymore.

**Comment by bluca** [comment]
With the new module load patchset, the modprobe hack won't be necessary anymore. Once I backport that patchset I'll take it out.
