### ISSUE TITLE
Can't install primus from ppa:bumblebee/testing after HWE 16.04

### ISSUE THREAD

**Issue by Void97** [Bumblebee-Project/bumblebee-ppa#43]
I've installed the latest Hardware Enablement Stack on KDE Neon 5.9.4, and whereas `bumblebee-nvidia` package from `ppa:bumblebee/testing` works fine after [these changes](https://github.com/Bumblebee-Project/bumblebee-ppa/pull/42), `primus` package goes in conflict with `xorg`:

`sudo apt install primus
...
The following packages will be REMOVED:
  neon-desktop xorg xserver-xorg-core-hwe-16.04 xserver-xorg-hwe-16.04 xserver-xorg-input-all-hwe-16.04 xserver-xorg-input-evdev-hwe-16.04 xserver-xorg-input-synaptics-hwe-16.04
  xserver-xorg-input-wacom-hwe-16.04 xserver-xorg-video-all-hwe-16.04 xserver-xorg-video-amdgpu-hwe-16.04 xserver-xorg-video-ati-hwe-16.04 xserver-xorg-video-fbdev-hwe-16.04
  xserver-xorg-video-nouveau-hwe-16.04 xserver-xorg-video-qxl-hwe-16.04 xserver-xorg-video-radeon-hwe-16.04 xserver-xorg-video-vesa-hwe-16.04 xserver-xorg-video-vmware-hwe-16.04`

**Comment by bluca** [comment]
thanks, will solve in the next couple of days

**Comment by bluca** [comment]
@Void97 I've uploaded a new version in the testing PPA, could you please give it a run and report back if everything's all right?

**Comment by Void97** [comment]
Yep, I'll give it a try and report back as soon as possible. Thanks for your work.

**Comment by Void97** [comment]
`primusrun` works like a charm, either with `vblank_mode=` or without it. Thank you very much.

**Comment by bluca** [comment]
no problem, thanks for checking
