### ISSUE TITLE
bumblebee.conf still points to nvidia-current, even though newer nvidia driver was installed

### ISSUE THREAD

**Issue by sudopluto** [Bumblebee-Project/bumblebee-ppa#46]
perhaps there is a way to automatically update the nvidia driver section of the conf to use the currently installed driver?

**Comment by bluca** [comment]
The driver should provide modprobe aliases so that current always works. We do that in debian, but Ubuntu doesn't always

**Comment by sudopluto** [comment]
i see, let me poke the driver ppa team
