### ISSUE TITLE
Can't install primus from ppa:bumblebee/testing after HWE 18.04

### ISSUE THREAD

**Issue by finostro** [Bumblebee-Project/bumblebee-ppa#51]
Hello,
I am trying to install bumblebee, but it wants to remove the xserver-xorg-hwe-18.04, could the dependencies be updated as was done with  xserver-xorg-hwe-16.04 in issue #43 ?

I had to install xserver-xorg-hwe-18.04 to fix horrible performance of the ubuntu UI, in ubuntu 18.04. 
Will try if xserver-xorg-hwe-16.04 also fixes the issue. 

Edit: xserver-xorg-hwe-16.04 did fix it, though if possible it could also work with the 18.04 version.

Thanks!

**Comment by kelebek333** [comment]
You can try to install following edited packages. I only manually added xserver-xorg-core-hwe-18.04 into control files for alternative dependency.

[edited.zip](https://github.com/Bumblebee-Project/bumblebee-ppa/files/3118450/edited.zip)

**Comment by bluca** [comment]
It's been fixed now

**Comment by kelebek333** [comment]
> It's been fixed now

@bluca Hi,

Thank you for your efforts.

How to install fixed primus package? Are you going to add the fixed primus package to the ppa repository?

**Comment by bluca** [comment]
primus is already in the ubuntu's repository, is that not working?

**Comment by kelebek333** [comment]
Primus package on bionic repo conflict with xserver-xorg-legacy-hwe-18.04 meta package. If I want to install primus package, apt remove all packages related xserver-xorg-legacy-hwe-18.04.

> sudo apt install primus 
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> The following package was automatically installed and is no longer required:
>   xserver-xorg-legacy-hwe-18.04
> Use 'sudo apt autoremove' to remove it.
> The following additional packages will be installed:
>   bbswitch-dkms bumblebee primus-libs socat xserver-xorg-core
> Suggested packages:
>   bumblebee-nvidia nvidia-driver-libs-nonglvnd xfonts-100dpi | xfonts-75dpi
> Recommended packages:
>   primus-libs-ia32
> The following packages will be REMOVED:
>   xorg xserver-xorg-core-hwe-18.04 xserver-xorg-hwe-18.04
>   xserver-xorg-input-all-hwe-18.04 xserver-xorg-input-libinput-hwe-18.04
>   xserver-xorg-video-all-hwe-18.04 xserver-xorg-video-amdgpu-hwe-18.04
>   xserver-xorg-video-ati-hwe-18.04 xserver-xorg-video-fbdev-hwe-18.04
>   xserver-xorg-video-intel-hwe-18.04 xserver-xorg-video-nouveau-hwe-18.04
>   xserver-xorg-video-qxl-hwe-18.04 xserver-xorg-video-radeon-hwe-18.04
>   xserver-xorg-video-vesa-hwe-18.04 xserver-xorg-video-vmware-hwe-18.04
> The following NEW packages will be installed:
>   bbswitch-dkms bumblebee primus primus-libs socat xserver-xorg-core
> 0 upgraded, 6 newly installed, 15 to remove and 5 not upgraded.
> Need to get 1473 kB/1814 kB of archives.
> After this operation, 3640 kB disk space will be freed.
> Do you want to continue? 

Could you add xserver-xorg-legacy-hwe-18.04 for alternative depency  to primus package.

> Depends: bumblebee, socat, primus-libs (= 0~20150328-7), xserver-xorg-core (>= 2:1.18.3-2) | xserver-xorg-legacy-hwe-18.04 (>= 2:1.20.1-3) | xserver-xorg-video-intel (>= 2:2.99.917)

**Comment by kelebek333** [comment]
@bluca, primus package for Ubuntu 18.04 conflict with  xserver-xorg-legacy-hwe-18.04. Can you add alternative depency to primus package (for bionic/universe repo or bumblebee/testing ppa)

**Comment by bluca** [comment]
uploaded to the testing ppa, should be available in a few minutes

**Comment by kelebek333** [comment]
@bluca , thank you very much for your interest.
